### ISSUE TITLE
Testing Checklist

### ISSUE THREAD

**Issue by EpicPantalones** [EpicPantalones/AutoFrog#5]
The following test must be completed for the design to be considered complete:
**Hardware Tests**
- [x] 12v Regulator output tested
- [x] 5v Regulator output tested
- [x] channeled relay tested to ensure proper toggles
- [x] Rpi outputs tested
- [ ] Humidity sensor gives valid data
- [ ] Items stay securely in mechanical housing
- [x] AC input tested

**Software Tests**
- [ ] Rpi can read humidity sensor
- [ ] Rpi can toggle switches on and off
- [x] Rpi can communicate across socket
- [x] Rpi can receive input from user endpoint
- [ ] Rpi software restarts properly after power-loss

Tests may be added or removed within this thread. _Do not mark this issue as complete_

**Comment by EpicPantalones** [comment]
New Test:
- [ ] logic shifter successfully changes from 3.3 to 5v
